In [ ]:
import pandas as pd
import numpy as np
import re
import datetime
import matplotlib.pyplot
from pandas_profiling import ProfileReport

pd.set_option('display.max_colwidth', -1)

In [ ]:
#if there is an issue with import try:

!pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

In [10]:
inspections = pd.read_csv("prohlidky.csv")
inspections = inspections.drop(['Unnamed: 0'], axis=1)
inspections.DatKont = pd.to_datetime(inspections.DatKont)
inspections.DatPrvReg = pd.to_datetime(inspections.DatPrvReg)
display(inspections.head())
display(inspections.info())
display(inspections.describe())

,STK,DrTP,VIN,DatKont,TypMot,TZn,DrVoz,ObchOznTyp,Ct,DatPrvReg,Km,ZavA,ZavB,ZavC,VyslSTK,VyslEmise
0,3122,Evidencni kontrola,JMZBLA2G601258504,2018-01-02 11:03:12.833,LF,MAZDA,OSOBNI AUTOMOBIL,3,M1,2011-02-10,84818,0,0,0,zpusobile,---
1,3205,Evidencni kontrola,4150417,2018-01-02 11:06:07.617,EM150.2,MZ,MOTOCYKL,ETZ 150,L3e,1989-01-01,38828,0,0,0,zpusobile,---
2,3114,Evidencni kontrola,VF3MJAHXHGS280168,2018-01-02 11:15:08.083,AH01,PEUGEOT,OSOBNI AUTOMOBIL,3008,M1,2017-01-09,39227,0,0,0,zpusobile,---
3,3618,Evidencni kontrola,4699845,2018-01-02 11:19:22.967,1202,SKODA,OSOBNI AUTOMOBIL,1202,M1,1979-06-04,38951,0,0,0,zpusobile,---
4,3748,Evidencni kontrola,WF0SXXGCDSAU06730,2018-01-02 11:30:25.420,GPDC,FORD,OSOBNI AUTOMOBIL,FOCUS (DA3),M1,2010-06-29,254194,0,0,0,zpusobile,---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3728369 entries, 0 to 3728368
Data columns (total 16 columns):
STK           int64
DrTP          object
VIN           object
DatKont       datetime64[ns]
TypMot        object
TZn           object
DrVoz         object
ObchOznTyp    object
Ct            object
DatPrvReg     datetime64[ns]
Km            int64
ZavA          int64
ZavB          int64
ZavC          int64
VyslSTK       object
VyslEmise     object
dtypes: datetime64[ns](2), int64(5), object(9)
memory usage: 455.1+ MB

None

                STK            Km          ZavA          ZavB          ZavC
count  3.728369e+06  3.728369e+06  3.728369e+06  3.728369e+06  3.728369e+06
mean   3.525718e+03  1.583200e+05  2.001051e+00  1.660005e-01  9.282075e-03
std    3.388045e+02  1.429099e+05  2.571117e+00  8.030010e-01  1.350142e-01
min    3.100000e+03  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    3.245000e+03  6.002300e+04  0.000000e+00  0.000000e+00  0.000000e+00
50%    3.524000e+03  1.457220e+05  1.000000e+00  0.000000e+00  0.000000e+00
75%    3.739000e+03  2.210340e+05  3.000000e+00  0.000000e+00  0.000000e+00
max    9.999000e+03  9.944330e+06  4.400000e+01  3.700000e+01  2.300000e+01

In [ ]:
profile = ProfileReport(inspections, title='Inspections Profiling Report', html={'style':{'full_width':True}})
#minimal=True
profile.to_file(output_file="profile_report.html")